thekorn/xandr

- packages/xandr/example/lib/main.dart
- packages/xandr/example/lib/main_interstitial.dart
👌 improve(main.dart): add sample text between AdBanners for better visual separation
🔧 refactor(main.dart, main_interstitial.dart): use Scaffold and AppBar for consistent UI structure
> style(main.dart, main_interstitial.dart): enhance UI with Scaffold, AppBar and theme

- packages/xandr/example/lib/main.dart
- packages/xandr/lib/load_mode.dart
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/BannerViewFactory.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/listeners/XandrAdListener.kt
🔧 refactor(load_mode.dart): make pixelOffset optional in LoadMode.whenInViewport
🔧 refactor(XandrAdListener.kt): comment out resizeWhenLoaded for debugging and add more detailed logging
🔧 refactor(XandrAdListener.kt): change resize method to accept widgetId for better logging
🔧 refactor(XandrAdListener.kt): add null check for view in onAdLoaded method to prevent potential null pointer exception
> 🔧 refactor(main.dart): comment out non-working code for debugging

- .github/dependabot.yaml
✨ feat(dependabot.yaml): add gradle and swift package ecosystems for android and ios directories respectively for better dependency management
> refactor: dependabot.yaml update directory paths for package ecosystems to reflect new project structure

- cspell.json
- melos.yaml
- packages/xandr/test/xandr_test.mocks.dart
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/Xandr.g.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/XandrPlugin.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/XandrPluginData.kt
- packages/xandr_android/lib/src/messages.g.dart
- packages/xandr_android/lib/xandr_android.dart
- packages/xandr_android/pigeons/messages.dart
- packages/xandr_android/pubspec.yaml
- packages/xandr_android/test/xandr_android_test.mocks.dart
- packages/xandr_platform_interface/lib/src/interface.dart
- packages/xandr_platform_interface/lib/src/method_channel.dart
- packages/xandr_platform_interface/lib/src/types.dart
- packages/xandr_platform_interface/test/xandr_platform_interface_test.mocks.dart
> feat: implement ways to set and get external user ids (fixes: #21)

- packages/xandr/example/lib/main_multi_ad_request.dart
- packages/xandr/lib/multiadrequest_builder.dart
> feat: Add new MultiAdRequestBuilder class to facilitate creation and management of multiple ad requests

- packages/xandr/test/xandr_test.mocks.dart
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/Xandr.g.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/XandrPlugin.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/BannerViewOptions.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/ads/BannerAd.kt
- packages/xandr_android/lib/src/messages.g.dart
- packages/xandr_android/lib/xandr_android.dart
- packages/xandr_android/pigeons/messages.dart
- packages/xandr_android/test/xandr_android_test.mocks.dart
- packages/xandr_platform_interface/lib/src/interface.dart
- packages/xandr_platform_interface/test/xandr_platform_interface_test.mocks.dart
> feat: implement GDPR consent handling for android (fixes: #36)

- packages/xandr_ios/ios/Classes/FlutterState.swift
- packages/xandr_ios/ios/Classes/MultiAdRequestRegistry.swift
- packages/xandr_ios/ios/Classes/Utils.swift
- packages/xandr_ios/ios/Classes/XandrPlugin.swift
- packages/xandr_ios/ios/Classes/models/ads/InterstitialAd.swift
- packages/xandr_ios/ios/Classes/pigeons/Xandr.g.swift
- packages/xandr_ios/lib/src/messages.g.dart
- packages/xandr_ios/lib/xandr_ios.dart
- packages/xandr_ios/pigeons/messages.dart
- packages/xandr_ios/pubspec.yaml
- packages/xandr_platform_interface/lib/src/interface.dart
> Ios part implementation

- packages/xandr/lib/xandr.dart
- packages/xandr/test/xandr_test.mocks.dart
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/Xandr.g.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/XandrPlugin.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/FlutterState.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/ads/BannerAd.kt
- packages/xandr_android/lib/src/messages.g.dart
- packages/xandr_android/lib/xandr_android.dart
- packages/xandr_android/pigeons/messages.dart
- packages/xandr_android/test/xandr_android_test.mocks.dart
- packages/xandr_ios/ios/Classes/FlutterState.swift
- packages/xandr_ios/ios/Classes/XandrPlugin.swift
- packages/xandr_ios/ios/Classes/pigeons/Xandr.g.swift
- packages/xandr_ios/lib/src/messages.g.dart
- packages/xandr_ios/lib/xandr_ios.dart
- packages/xandr_ios/pigeons/messages.dart
- packages/xandr_ios/test/xandr_ios_test.mocks.dart
- packages/xandr_platform_interface/lib/src/interface.dart
- packages/xandr_platform_interface/lib/src/method_channel.dart
- packages/xandr_platform_interface/test/xandr_platform_interface_test.mocks.dart
implementation of the publisherId
> feat: 79 feat implement publisherid

- .github/workflows/xandr.yaml
- .github/workflows/xandr_android.yaml
- .github/workflows/xandr_ios.yaml
- .github/workflows/xandr_platform_interface.yaml
- .opencommitignore
- CONTRIBUTING.md
- melos.yaml
- packages/xandr/CONTRIBUTING.md
- packages/xandr_android/lib/src/messages.g.dart
- packages/xandr_ios/ios/Classes/pigeons/Xandr.g.swift
- packages/xandr_ios/lib/src/messages.g.dart
- pubspec.yaml
> feat: Various updates

- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/FlutterState.kt
- packages/xandr_ios/ios/Classes/Errors.swift
- packages/xandr_ios/ios/Classes/FlutterState.swift
- packages/xandr_ios/ios/Classes/Logging.swift
- packages/xandr_ios/ios/Classes/XandrPlugin.swift
- packages/xandr_ios/ios/Classes/pigeons/Xandr.g.swift
- packages/xandr_ios/lib/src/messages.g.dart
- packages/xandr_ios/lib/xandr_ios.dart
- packages/xandr_ios/pigeons/messages.dart
- packages/xandr_ios/test/xandr_ios_test.mocks.dart
> fix: iOS fix stack overflow on ads loaded wheninviewport

- melos.yaml
- packages/xandr/pubspec.yaml
- packages/xandr_android/pubspec.yaml
- packages/xandr_ios/pubspec.yaml
- packages/xandr_platform_interface/pubspec.yaml
- pubspec.yaml
> build: proper integration of pana in melos

- packages/xandr_ios/ios/Classes/XandrPlugin.swift
…hod.
Added a parent view controller reference inside the interstitial ad "display" method.
> iOS Interstitials fix

- packages/xandr/lib/ad_banner.dart
> Adbanner initial size

- packages/xandr/example/lib/main.dart
- packages/xandr_ios/ios/Classes/models/FlutterState.swift
- packages/xandr_ios/ios/Classes/models/ads/BannerAd.swift
- Enhance ad handling and configuration in SDK
- Enhance ad configuration options in BannerAd to support new functionalities like resizing, auto-refreshing, and lazy loading.
- Change error handling in BannerAd to respond specifically to ad request failures.
- Introduce error handling method `onAdLoadedError` in FlutterState for improved error management.
- Temporarily disable certain ad features in main.dart for further evaluation and testing.
> feat: add some missing implementations on iOS

- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/ads/BannerAd.kt
> prevent multiple loadad calls on android banner

- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/ads/BannerAd.kt
> implement android lifecycle events for banner

- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/BannerViewContainer.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/Xandr.g.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/XandrPlugin.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/listeners/AdInitListener.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/listeners/XandrAdListener.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/BannerViewOptions.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/FlutterState.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/ads/BannerAd.kt
> fix imports

- packages/xandr/example/lib/main.dart
- packages/xandr/lib/ad_banner.dart
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/Xandr.g.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/listeners/XandrAdListener.kt
- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/models/ads/BannerAd.kt
- packages/xandr_android/lib/src/messages.g.dart
- packages/xandr_android/lib/xandr_android.dart
- packages/xandr_android/pigeons/messages.dart
- packages/xandr_ios/ios/Classes/models/FlutterState.swift
- packages/xandr_ios/ios/Classes/models/ads/BannerAd.swift
- packages/xandr_ios/ios/Classes/pigeons/Xandr.g.swift
- packages/xandr_ios/lib/src/messages.g.dart
- packages/xandr_ios/lib/xandr_ios.dart
- packages/xandr_ios/pigeons/messages.dart
- packages/xandr_platform_interface/lib/src/types.dart
Fix iOS clickThroughAction implementation and add onAdClicked callback
> fix: fix clickThroughAction ios implementation + onAdClicked callback

- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/listeners/XandrAdListener.kt
> fix: null safe call on xandr native ad response

- packages/xandr_android/android/src/main/kotlin/de/thekorn/xandr/XandrPlugin.kt
Also remove some very unnecessary debug logs
> fix: dont recursivly call the onDetachFromActivity() in the android plugin (#141)

- packages/xandr/lib/xandr.dart
- packages/xandr_platform_interface/lib/src/interface.dart
Fix wrong assert on setAutoRefreshInterval
> fix: assert on set auto refresh interval method

- packages/xandr_android/android/build.gradle
- packages/xandr_android/android/gradle/wrapper/gradle-wrapper.properties
> chore: Update various android dependencies

- .github/workflows/xandr.yaml
- melos.yaml
- Enhance code coverage management by adding scripts for merging trace files and checking coverage.
- Modify test configuration to run Flutter tests with coverage and integrate trace file merging.
- Update GitHub Actions to include a minimum coverage parameter in the build workflow.
> fix: Enhance code coverage handling and reporting

- packages/xandr/example/ios/Runner.xcodeproj/project.pbxproj
- packages/xandr_android/android/build.gradle
- packages/xandr_ios/ios/xandr_ios.podspec
> chore: Upgrade xandr sdks
